PUT  http://localhost:8080/compcorp/2
Content-Type: application/json

{
        "massa": 75,
        "imc": 29,
        "gordura_corporal": 15,
        "gordura_visceral": 5,
        "metabolismo_basal": 2500,
        "musculos_esqueleticos": 55,
        "idade_corporal": 15
}