PUT  http://localhost:8080/pacientes/1
Content-Type: application/json

{
    "nome":"Debora",
    "idade":"29",
    "sexo":"Feminino",
    "celular":"(21)97878765",
    "cpf":"11111111111",
    "email":"blabla@hotmail.com",
    "data_nascimento":"18/02/1994"
 }