POST  http://localhost:8080/pacientes/
Content-Type: application/json

{
    "nome":"Felipe",
    "idade":"29",
    "sexo":"Feminino",
    "celular":"(21)97878765",
    "cpf":"1233214345",
    "email":"blabla@hotmail.com",
    "data_nascimento":"30/10/1994"
 }